version: '3.4'

services:
  sqldata:
    container_name: sqldata
    environment:
      - SA_PASSWORD=secretpw123
      - ACCEPT_EULA=Y
      - MSSQL_PID-Express
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
        
  ravendb:
    container_name: ravendb
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    restart: always
    ports:
      - "8080:8080"
      - "38888:38888"
    volumes:
      - ravendbdata:/var/ravendb/data

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
  
  likr.posts:
    container_name: likr.posts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=PostsDb;User Id=sa;Password=secretpw123;"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "IdentityUrl=http://likr.identity"
    restart: unless-stopped
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "8001:80"
  
  likr.comments:
    container_name: likr.comments
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database:Urls:0=http://ravendb:8080"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "IdentityUrl=http://likr.identity"
    restart: unless-stopped
    depends_on:
      - ravendb
      - rabbitmq
    ports:
      - "8002:80"

  likr.likes:
    container_name: likr.likes
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=LikesDb;User Id=sa;Password=secretpw123;"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "IdentityUrl=http://likr.identity"
    restart: unless-stopped
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "8003:80"

#  likr.identity:
#    container_name: likr.identity
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=IdentityDb;User Id=sa;Password=secretpw123;"
#      - "ServiceUrl=http://likr.identity"
##      - "AllowedOrigins:0=http://likr.client" Insert deployment URL when deployed
#    restart: unless-stopped
#    depends_on:
#      - sqldata
#    ports:
#      - "8004:80"

  likr.identity.server:
    container_name: likr.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=IdentityDb;User Id=sa;Password=secretpw123;"
      -  "ServiceUrl=http://likr.identity"
    depends_on:
      - sqldata
    ports:
      - "8004:80"

  likr.gateway:
    container_name: likr.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - "IdentityUrl=http://likr.identity"
    ports:
      - "5200:80"

  likr.client:
    container_name: likr.client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "Local:ClientId=client-spa-container"
    ports:
      - "8100:80"
#      - "8100:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
