version: '3.4'

services:
  sqlserver:
    container_name: sqlserver
    environment:
      SA_PASSWORD: "secretpw123"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
  
  likr.posts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro