version: '3.4'

services:
  sqldata:
    container_name: sqldata
    environment:
      - SA_PASSWORD=secretpw123
      - ACCEPT_EULA=Y
      - MSSQL_PID-Express
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
  
  ravendb:
    container_name: ravendb
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    restart: always
    ports:
      - "8080:8080"
      - "38888:38888"
    volumes:
      - ravendbdata:/var/ravendb/data

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
  
  likr.posts:
    container_name: likr.posts
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=PostsDb;User Id=sa;Password=secretpw123;"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "IdentityUrl=http://likr.identity"
    restart: unless-stopped
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "80"
  
  likr.comments:
    container_name: likr.comments
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "Database:Urls:0=http://ravendb:8080"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "IdentityUrl=http://likr.identity"
    restart: unless-stopped
    depends_on:
      - ravendb
      - rabbitmq
    ports:
      - "80"

  likr.likes:
    container_name: likr.likes
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=LikesDb;User Id=sa;Password=secretpw123;"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
      - "IdentityUrl=http://likr.identity"
    restart: unless-stopped
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "80"

  likr.identity.server:
    container_name: likr.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=IdentityDb;User Id=sa;Password=secretpw123;"
      - "RabbitMq=amqp://guest:guest@rabbitmq:5672"
    #      - "ServiceUrl=http://likr.identity" # Change to deployed URL once deployed
    #      - "Urls:BaseUri=http://localhost:8100"  # Change to deployed URL once deployed
    depends_on:
      - sqldata
    ports:
      - "8004:80"

  likr.gateway:
    container_name: likr.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "IdentityUrl=http://likr.identity"
    depends_on:
      - likr.identity
    ports:
      - "5200:80"

  likr.client:
    container_name: likr.client
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      #      - "Authority=http://localhost:8004" Change to deployed URL once deployed
      - "ServiceUrl=http://likr.client:8100"
    depends_on:
      - likr.identity
    ports:
      - "8100:80"
