version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  ravendb:
    image: ravendb/ravendb

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  likr.posts:
    image: ${DOCKER_REGISTRY-}likrposts
    build:
      context: .
      dockerfile: src/Services/Likr.Posts/Dockerfile

  likr.comments:
    image: ${DOCKER_REGISTRY-}likrcomments
    build:
      context: .
      dockerfile: src/Services/Likr.Comments/Dockerfile

  likr.likes:
    image: ${DOCKER_REGISTRY-}likrlikes
    build:
      context: .
      dockerfile: src/Services/Likr.Likes/Dockerfile

volumes:
  mssqldata:
  rabbitmqdata:
  ravendbdata: