version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  likr.posts:
    image: ${DOCKER_REGISTRY-}likrposts
    build:
      context: .
      dockerfile: src/Likr.Posts/Dockerfile

  likr.comments:
    image: ${DOCKER_REGISTRY-}likrcomments
    build:
      context: .
      dockerfile: src/Likr.Comments/Dockerfile

  likr.likes:
    image: ${DOCKER_REGISTRY-}likrlikes
    build:
      context: .
      dockerfile: src/Likr.Likes/Dockerfile

