version: '3.4'

services:
  sqldata:
    container_name: sqldata
    environment:
      - SA_PASSWORD=secretpw123
      - ACCEPT_EULA=Y
      - MSSQL_PID-Express
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
        
  ravendb:
    container_name: ravendb
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    ports:
      - "8080:8080"
      - "38888:38888"
    volumes:
      - ravendbdata:/var/ravendb/data

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
  
  likr.posts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=sqldata;Database=PostsDb;User Id=sa;Password=secretpw123;"
    depends_on:
      - sqldata
    ports:
      - "8001:80"
  
  likr.comments:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database:Urls:0=http://ravendb:8080"
    ports:
      - "8002:80"

  likr.likes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"