version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  ravendb:
    image: ravendb/ravendb

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  likr.posts:
    image: ${DOCKER_REGISTRY-}likrposts
    build:
      context: .
      dockerfile: src/Services/Likr.Posts/Likr.Posts/Dockerfile

  likr.comments:
    image: ${DOCKER_REGISTRY-}likrcomments
    build:
      context: .
      dockerfile: src/Services/Likr.Comments/Likr.Comments/Dockerfile

  likr.likes:
    image: ${DOCKER_REGISTRY-}likrlikes
    build:
      context: .
      dockerfile: src/Services/Likr.Likes/Likr.Likes/Dockerfile

  likr.gateway:
    image: ${DOCKER_REGISTRY-}likrgateway
    build:
      context: .
      dockerfile: src/Gateway/Likr.Gateway/Dockerfile

  likr.identity:
    image: ${DOCKER_REGISTRY-}likridentity
    build:
      context: .
      dockerfile: src/Services/Likr.Identity/Likr.Identity/Dockerfile

#  likr.client:
#    image: ${DOCKER_REGISTRY-}likrclient
#    build:
#      context: .
#      dockerfile: src/Client/Likr.Client/Dockerfile

volumes:
  mssqldata:
  rabbitmqdata:
  ravendbdata:


